src/Entity/Video.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\VideoRepository")
 */
class Video
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string")
     * @Assert\File()
     */
    private $filePath;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="videos")
     */
    private $User;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Subtitle", mappedBy="video")
     */
    private $subtitles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="video")
     */
    private $comments;


    public function __construct()
    {
        $this->created = new \DateTime('now');
        $this->updated = new \DateTime('now');
        $this->subtitles = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFilePath(): ?string
    {
        return $this->filePath;
    }

    public function setFilePath(string $filePath): self
    {
        $this->filePath = $filePath;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * @return Collection|Subtitle[]
     */
    public function getSubtitles(): Collection
    {
        return $this->subtitles;
    }

    public function addSubtitle(Subtitle $subtitle): self
    {
        if (!$this->subtitles->contains($subtitle)) {
            $this->subtitles[] = $subtitle;
            $subtitle->setVideo($this);
        }

        return $this;
    }

    public function removeSubtitle(Subtitle $subtitle): self
    {
        if ($this->subtitles->contains($subtitle)) {
            $this->subtitles->removeElement($subtitle);
            // set the owning side to null (unless already changed)
            if ($subtitle->getVideo() === $this) {
                $subtitle->setVideo(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setVideo($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getVideo() === $this) {
                $comment->setVideo(null);
            }
        }

        return $this;
    }
}

src/Form/VideoType.php
<?php

namespace App\Form;

use App\Entity\Video;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VideoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('description', TextType::class)
            ->add('filePath', FileType::class, ['label' => 'Video file'] )
            ->add('active', CheckboxType::class, [
                'label'    => 'Czy aktywny',
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Video::class,
        ]);
    }
}

src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Entity\Subtitle;
use App\Entity\Video;
use App\Form\VideoType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class VideoController extends AbstractController
{
    /**
     * @Route("/", name="last_video")
     */
    public function index(Request $request, EntityManagerInterface $em)
    {
        $videoRepository = $em->getRepository(Video::class);
        $actives = $videoRepository->findBy(['active' => true], ['id' => 'DESC']);
        return $this->render('video/index.html.twig', [
            'vidoes' => $actives,
            'videoPath' => $this->getParameter('video_directory')
        ]);
    }


    /**
     * @Route("/video/{id}", name="video_store")
     */
    public function store(int $id, Request $request, EntityManagerInterface $em) {
        $videoRepository = $em->getRepository(Video::class);
        $model = $videoRepository->find($id);

        $encoders = [new JsonEncoder()]; // If no need for XmlEncoder
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);

        $jsonObject = $serializer->serialize($model->getSubtitles(), 'json', [
            'circular_reference_handler' => function ($object) {
                return $object->getId();
            }
        ]);

        return $this->render('video/store.html.twig', [
            'video' => $model,
            'subtitles' => $jsonObject,
            'videoPath' => $this->getParameter('video_directory')
        ]);
    }

    /**
     * @Route("myVideos", name="my_movies")
     */
    public function myMovies(Request $request, EntityManagerInterface $em)
    {
        $videoRepository = $em->getRepository(Video::class);
        $myMovieList = $videoRepository->findBy(['User' => $this->getUser()]);

        return $this->render('video/my_movies.html.twig', [
            'vidoes' => $myMovieList,
        ]);
    }


    /**
     * @Route("myVideos/edit/{id}", name="edit_video")
     */
    public function edit(int $id, EntityManagerInterface $em)
    {
        $videoRepository = $em->getRepository(Video::class);
        $model = $videoRepository->find($id);

        return $this->render('video/edit.html.twig', [
            'model' => $model,
            'videoPath' => $this->getParameter('video_directory')
        ]);
    }


    /**
     * @Route("myVideos/delete/{id}", name="remove_video")
     */
    public function remove(int $id, EntityManagerInterface $em)
    {
        $videoRepository = $em->getRepository(Video::class);
        $model = $videoRepository->find($id);

        $em->remove($model);
        $em->flush();

        return $this->render('video/my_movies.html.twig');
    }

    /**
     * @Method("POST")
     * @Route("myVideos/{id}/addSubtitle", name="add_subtitle")
     */
    public function addSubtitle(int $id, Request $request, EntityManagerInterface $em) {
        $videoRepository = $em->getRepository(Video::class);
        $video = $videoRepository->find($id);

        $start = $request->get('start');
        $duration = $request->get('duration');
        $text = $request->get('text');

        $subtitle = new Subtitle();
        $subtitle->setStart($start);
        $subtitle->setDuration($duration);
        $subtitle->setText($text);
        $subtitle->setVideo($video);

        $em->persist($subtitle);
        $em->flush();

        $encoders = [new JsonEncoder()]; // If no need for XmlEncoder
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);

        $jsonObject = $serializer->serialize($subtitle, 'json', [
            'circular_reference_handler' => function ($object) {
                return $object->getId();
            }
        ]);

        return new Response($jsonObject, 200, ['Content-Type' => 'application/json']);
    }


    /**
     * @Route("myVideos/{id}/removeSubtitle/{idSub}", name="remove_subtitle")
     */
    public function removeSubtitle(int $id, int $idSub, Request $request, EntityManagerInterface $em) {
        $subtitleRepository = $em->getRepository(Subtitle::class);
        $subtitle = $subtitleRepository->find($idSub);

        $em->remove($subtitle);
        $em->flush();

        return $this->redirectToRoute('edit_video', ['id' => $id]);
    }


    /**
     * @Route("/upload", name="upload")
     */
    public function uploadVideo(Request $request, EntityManagerInterface $em)
    {
        $video = new Video();
        $form = $this->createForm(VideoType::class, $video);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var UploadedFile $file */
            $file = $form['filePath']->getData();
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();


            // Move the file to the directory where brochures are stored
            try {
                $file->move(
                    $this->getParameter('video_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }


            $video->setFilePath($fileName);
            $video->setUser($this->getUser());
            $video->setCreated(new \DateTime('now'));
            $video->setUpdated(new \DateTime('now'));

            $em->persist($video);
            $em->flush();


            return $this->redirect($this->generateUrl('my_movies'));

        }

        return $this->render('video/upload.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


}

templates/video/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edycja!{% endblock %}

{% block body %}


    <!--suppress ALL -->
    <div class="container">

        <div class="row">
            <div class="col">
                <video id="video" width="100%" src="{{ '/uploads/videos' ~ '/' ~  model.filePath }}" controls >
                    Przepraszamy ale Twoja przeglądarka nie potrafi odtwarzać filmów za pomocą HTML5.
                    Nie przejmuj się, bo <a href="{{ videoPath ~ '/' ~  model.filePath }}">możesz go stąd pobrać</a>
                    i oglądać za pomocą swojego ulubionego odtwarzacza!
                </video>
            </div>

            <div class="col">
                <div class="button-group float-right mb-4">
                    <button id="openModal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Dodaj tekst do filmu</button>
                    <button class=" btn btn-warning">#</button>
                </div>

                {% if model.subtitles.count() %}
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Czas rozpoczęcia [s]</th>
                            <th scope="col">Długosc wyswietlenia [s]</th>
                            <th scope="col">Tekst</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for subtitle in model.subtitles %}
                            <tr>
                                <td>{{ subtitle.start }}</td>
                                <td>{{ subtitle.duration }}</td>
                                <td>{{ subtitle.text }}</td>
                                <td>
                                    <a class="btn btn-sm btn-danger" href="{{ path('remove_subtitle', {id: model.id, idSub: subtitle.id} ) }}">Usuń</a>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>

                {% else %}
                    <h2>Brak napisów</h2>
                {% endif %}
            </div>
        </div>

    </div>


    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Dodawanie tekstu</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="addText">
                    <div class="modal-body">

                        <div class="form-group">
                            <label for="subtitle">Napis na video</label>
                            <input type="text" class="form-control" name="subtitle" id="subtitle" required>
                        </div>

                        <div class="form-group">
                            <label for="start">Czas pojawienia się napisu [s]</label>
                            <input type="number" step="any"  class="form-control" name="start" id="start" required>
                        </div>

                        <div class="form-group">
                            <label for="duration">Dlugość wyświetlania [s]</label>
                            <input type="number" step="any"  class="form-control" name="duration" id="duration" required>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button id="saveButton" type="submit" class="btn btn-primary">Zapisz</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <script>
        var videoId = {{ model.id }}
        var video = document.getElementById('video');

        $('#openModal').click(function() {
            $('#start').val(video.currentTime)
        });


        $('#addText').submit(function (e) {
            e.preventDefault();
            var data =
            {
                'start': $('#start').val(),
                'duration': $('#duration').val(),
                'text': $('#subtitle').val()
            }


            $.ajax({
                type: 'POST',
                url: `/myVideos/${videoId}/addSubtitle`,
                data: data,
                dataType: 'json',
                success: function (res) {
                    location.reload();
                },
                error: function (error) {
                    console.log(error);
                }
            })
        })

    </script>

{% endblock %}

templates/video/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello VideoController!{% endblock %}

{% block body %}

    {% for row in vidoes %}
        <div class="row pt-5">
            <hr class="d-sm-none">
            <div class="col-sm-12">
                <h2>{{  row.name  }}</h2>
                <h5>{{  row.created | date("m/d/Y") }} </h5>
                <p>Dodano przez: {{ row.user.email }}</p>
                <p>{{ row.description }}</p>
                <div class="fakeimg">
                    <video class="video_redirect" data-id="{{ row.id }}" width="100%" src="{{ '/uploads/videos' ~ '/' ~  row.filePath }}"  >
                        Przepraszamy ale Twoja przeglądarka nie potrafi odtwarzać filmów za pomocą HTML5.
                        Nie przejmuj się, bo <a href="{{ videoPath ~ '/' ~  row.filePath }}">możesz go stąd pobrać</a>
                        i oglądać za pomocą swojego ulubionego odtwarzacza!
                    </video>

                </div>
                <p></p>
            </div>
        </div>
    {% else %}

        <h2 class="text-center">Brak filmów</h2>

    {% endfor %}


    <script>

        $('.video_redirect').click(function(e) {
            e.preventDefault();
            var id = $(this).data('id');
            window.location.href = `/video/${id}`
        })

    </script>

{% endblock %}

templates/video/my_movies.html.twig
{% extends 'base.html.twig' %}

{% block title %}Moja lista plików!{% endblock %}

{% block body %}

    <div class="row float-right p-4">
        <a class="btn btn-success" href="{{ path('upload') }}" >Dodaj film</a>
    </div>

    <table class="table table-bordered table-striped table-hover">
        <thead class="thead-inverse">
        <tr>
            <th>Id</th>
            <th>Nazwa </th>
            <th>Opis</th>
            <th>Data utworzenia</th>
            <th>Akcje</th>
        </tr>
        </thead>
        <tbody>
        {% for row in vidoes %}
            <tr>
                <td>{{ row.id }}</td>
                <td>{{ row.name }} </td>
                <td>{{ row.description }}</td>
                <td>{{ row.created | date("m/d/Y") }}</td>
                <td>
                    <a class="btn btn-sm btn-primary" href="{{ path('edit_video', {id: row.id} ) }}">Edycja</a>
                    <a class="btn btn-sm btn-danger" href="{{ path('remove_video', {id: row.id} ) }}">Usuń</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Brak filmów</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/video/remove.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usuwanie pliku!{% endblock %}

{% block body %}

{% endblock %}

templates/video/store.html.twig
{% extends 'base.html.twig' %}

{% block title %}Video !{% endblock %}

{% block body %}

    <style>
        #subtitles {
            bottom: 70px;
            left: 0;
            width: 100%;
            color: white;
            text-align: center;
            font-size: 17px;
            background: rgba(0,0,0,0.55);
        }
    </style>

    <div class="row pt-5">
        <hr class="d-sm-none">
        <div class="col-sm-12">
            <h2>{{  video.name  }}</h2>
            <h5>{{  video.created | date("m/d/Y") }} </h5>
            <p>Dodano przez: {{ video.user.email }}</p>
            <p>{{ video.description }}</p>
            <div class="fakeimg position-relative">
                <video id="video" class="video_redirect" data-id="{{ video.id }}" width="100%" src="{{ '/uploads/videos' ~ '/' ~  video.filePath }}" controls>
                    Przepraszamy ale Twoja przeglądarka nie potrafi odtwarzać filmów za pomocą HTML5.
                    Nie przejmuj się, bo <a href="{{ videoPath ~ '/' ~  video.filePath }}">możesz go stąd pobrać</a>
                    i oglądać za pomocą swojego ulubionego odtwarzacza!
                </video>

                <span id="subtitles" class="position-absolute">
                    Rozpocznij zeby zobaczyc napisy
                </span>
            </div>
        </div>
    </div>

    <div class="row pt-5">
        <hr>
        <div class="col-sm-12">
            <h2>Komenatarze</h2>

            {% if app.user == null %}
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Komenatrze tylko dla zalogowanych</h5>
                    </div>
                </div>
            {% else %}

                {% if video.comments.count() %}
                    {% for row in video.comments %}
                    <div class="card mt-4">
                        <div class="card-header">
                            {{ row.user.email }}

                            {% if row.user.email == app.user.email %}
                            <div class="float-right">
                                <a href="{{ path('remove_comment', {id: row.id, idVideo: video.id}) }}" class="btn btn-danger">Usuń</a>
                            </div>
                            {% endif %}
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ row.value }}</p>
                        </div>
                    </div>
                    {% endfor %}
                {% else %}
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Brak komenatrzy</h5>
                        </div>
                    </div>
                {% endif %}


                <button id="openModal" type="button" class="btn btn-primary mt-2" data-toggle="modal" data-target="#exampleModal">Dodaj komenatrz</button>
            {% endif %}


        </div>

    </div>

    <!-- Modal -->
    {% if app.user %}
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Dodawanie tekstu</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="addText">
                    <div class="modal-body">

                        <div class="form-group">
                            <label for="name">Użytkownik</label>
                            <input type="text" disabled class="form-control" value="{{ app.user.email }}" name="name" id="name">
                        </div>

                        <div class="form-group">
                            <label for="commentText">Tresc</label>
                            <textarea class="form-control" name="commentText" id="commentText" required>

                                    </textarea>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button id="saveButton" type="submit" class="btn btn-primary">Zapisz</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endif %}

    <script>
        var subtitles = JSON.parse({{ subtitles |json_encode|raw }});
        console.log(subtitles);
        var video = document.getElementById('video');

        video.ontimeupdate = function() {
            var found_names = $.grep(subtitles, function(v) {
                return video.currentTime >=  v.start && video.currentTime <= (v.start + v.duration);
            });

            if(found_names.length) {
                $('#subtitles').text(found_names[0].text);
            }
            else {
                $('#subtitles').text("");
            }
        };

    </script>

    <script>
        var videoId = {{ video.id }}

        $('#addText').submit(function (e) {
            e.preventDefault();
            var data =
                {
                    'videoId': videoId,
                    'value': $('#commentText').val(),
                };


            console.log('data');

            $.ajax({
                type: 'POST',
                url: `/comment`,
                data: data,
                dataType: 'json',
                success: function (res) {
                    location.reload();
                },
                error: function (error) {
                    console.log(error);
                }
            })
        })

    </script>

{% endblock %}

templates/video/upload.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dodaj plik!{% endblock %}

{% block body %}

    <h1>Dodawanie nowego filmu</h1>

    {{ form_start(form) }}
        {{ form_row(form.name) }}
        {{ form_row(form.description) }}
        {{ form_row(form.filePath) }}
        {{ form_row(form.active) }}
        <button  class="btn btn-lg btn-primary">Dodaj</button>
    {{ form_end(form) }}
{% endblock %}